# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4caf7c2c99f32befa6150abf6ff22a90d89bee1c38343083876de990f32c86e8abdd88fc3cdf3f5daae61d2dd06d19ad3d05f4363d81897e1b7dd4dc8136b62b

test:
  secret_key_base: fe1eba21e04bb13137b854d931bdf033b3671376dad46b9cdac1d8430ce626023b40364ef57dac676aab67bd0c5552620d0b0126d1eb4634f3aa08f5c9a93365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
